Revert "Fix undefined reference to x86_efi_facility"
This reverts commit e34d4dfe55f8d35bc9bf02ee60c3b1da4b0269a8.

Signed-off-by: Gary S. Robertson <gary.robertson@linaro.org>