MTD: MAP: _relaxed build fix
noticed build break on x86
In file included from drivers/mtd/chips/chipreg.c:11:0:
include/linux/mtd/map.h: In function â€˜inline_map_writeâ€™:
include/linux/mtd/map.h:420:3: error: implicit declaration of function â€˜writeb_relaxedâ€™ [-Werror=implicit-function-declaration]
   writeb_relaxed(datum.x[0], map->virt + ofs);
   ^
include/linux/mtd/map.h:422:3: error: implicit declaration of function â€˜writew_relaxedâ€™ [-Werror=implicit-function-declaration]
   writew_relaxed(datum.x[0], map->virt + ofs);
   ^
include/linux/mtd/map.h:424:3: error: implicit declaration of function â€˜writel_relaxedâ€™ [-Werror=implicit-function-declaration]
   writel_relaxed(datum.x[0], map->virt + ofs);

This commit breaks for x86:

commit 1e885fabb4b148110c43056dd16842d11cde11db
Author: Victor Kamensky <victor.kamensky@linaro.org>
Date:   Mon Jul 29 22:03:27 2013 -0700

mtd: map.h endian fix

Need to use endian neutral functions to read/write LE h/w registers. I.e
insted of __raw_readl and _raw_writel, readl_relaxed and writel_relaxed. If
the first just read/write register with memory barrier, the second will
byteswap it if host operates in BE mode.

Signed-off-by: Victor Kamensky <victor.kamensky@linaro.org>

Signed-off-by: Santosh Shukla <santosh.shukla@linaro.org>
Signed-off-by: Gary S. Robertson <gary.robertson@linaro.org>