Revert "Fix undefined reference to x86_efi_facility"
This reverts commit 8a529c0f6d3a1a613e5d039ca49bc3b8cf2417ff.

Signed-off-by: Gary S. Robertson <gary.robertson@linaro.org>