KVM:EVENTFD: fix implicit declaration on x86/_64
During compilation for x86 and x86_64, received the following warning:

virt/kvm/eventfd.c:493:2: error:
 implicit declaration of function 'kvm_vcpu_request_scan_ioapic'
 [-Werror=implicit-function-declaration]
  kvm_vcpu_request_scan_ioapic(kvm);

Commit 29f1b65 KVM:EVENTFD: Remove inclusion of irq.h
by Christoffer Dall addresses this issue in later kernels.
This backport incudes those portions of that patch which
are relevant in the 3.14 tree.

Signed-off-by: Gary S. Robertson <gary.robertson@linaro.org>